--------------------------------------------------------------------------------
-- BACKGROUND STARTING EQUIPMENT
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.background_starting_equipment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  background_id uuid NOT NULL,
  choice_group smallint NOT NULL DEFAULT 1,
  choice_option smallint NOT NULL,
  equipment_id uuid,
  notes jsonb NOT NULL DEFAULT '{}'::jsonb,
  quantity smallint NOT NULL DEFAULT 1,
  CONSTRAINT background_starting_equipment_entry_uniq
    UNIQUE NULLS NOT DISTINCT (
      background_id,
      choice_group,
      choice_option,
      equipment_id
    ),
  CONSTRAINT background_starting_equipment_background_id_fkey FOREIGN KEY (background_id) REFERENCES public.backgrounds(resource_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT background_starting_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipments(resource_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.background_starting_equipment OWNER TO postgres;
ALTER TABLE public.background_starting_equipment ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.background_starting_equipment TO anon;
GRANT ALL ON TABLE public.background_starting_equipment TO authenticated;
GRANT ALL ON TABLE public.background_starting_equipment TO service_role;

CREATE INDEX idx_background_starting_equipment_background_id
  ON public.background_starting_equipment USING btree (background_id);

CREATE INDEX idx_background_starting_equipment_equipment_id
  ON public.background_starting_equipment USING btree (equipment_id);


--------------------------------------------------------------------------------
-- BACKGROUND STARTING EQUIPMENT POLICIES
--------------------------------------------------------------------------------

CREATE POLICY "Users can read background starting equipment"
ON public.background_starting_equipment
FOR SELECT TO anon, authenticated
USING (
  public.can_read_resource(background_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can create background starting equipment"
ON public.background_starting_equipment
FOR INSERT TO authenticated
WITH CHECK (
  public.can_edit_resource(background_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can delete background starting equipment"
ON public.background_starting_equipment
FOR DELETE TO authenticated
USING (public.can_edit_resource(background_id));
