--------------------------------------------------------------------------------
-- CREATURE EQUIPMENT
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.creature_equipment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creature_id uuid NOT NULL,
  equipment_id uuid,
  quantity smallint NOT NULL DEFAULT 1,
  CONSTRAINT creature_equipment_creature_id_fkey FOREIGN KEY (creature_id) REFERENCES public.creatures(resource_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT creature_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipments(resource_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT creature_equipment_entry_uniq
    UNIQUE NULLS NOT DISTINCT (creature_id, equipment_id)
);

ALTER TABLE public.creature_equipment OWNER TO postgres;
ALTER TABLE public.creature_equipment ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.creature_equipment TO anon;
GRANT ALL ON TABLE public.creature_equipment TO authenticated;
GRANT ALL ON TABLE public.creature_equipment TO service_role;

CREATE INDEX idx_creature_equipment_creature_id
  ON public.creature_equipment USING btree (creature_id);

CREATE INDEX idx_creature_equipment_equipment_id
  ON public.creature_equipment USING btree (equipment_id);


--------------------------------------------------------------------------------
-- CREATURE EQUIPMENT POLICIES
--------------------------------------------------------------------------------

CREATE POLICY "Users can read creature equipment"
ON public.creature_equipment
FOR SELECT TO anon, authenticated
USING (
  public.can_read_resource(creature_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can create creature equipment"
ON public.creature_equipment
FOR INSERT TO authenticated
WITH CHECK (
  public.can_edit_resource(creature_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can delete creature equipment"
ON public.creature_equipment
FOR DELETE TO authenticated
USING (public.can_edit_resource(creature_id));
