--------------------------------------------------------------------------------
-- CHARACTER CLASS STARTING EQUIPMENT
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.character_class_starting_equipment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_class_id uuid NOT NULL,
  choice_group smallint NOT NULL DEFAULT 1,
  choice_option smallint NOT NULL,
  equipment_id uuid,
  quantity smallint NOT NULL DEFAULT 1,
  CONSTRAINT character_class_starting_equipment_entry_uniq
    UNIQUE NULLS NOT DISTINCT (
      character_class_id,
      choice_group,
      choice_option,
      equipment_id
    ),
  CONSTRAINT character_class_starting_equipment_character_class_id_fkey FOREIGN KEY (character_class_id) REFERENCES public.character_classes(resource_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT character_class_starting_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipments(resource_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.character_class_starting_equipment OWNER TO postgres;
ALTER TABLE public.character_class_starting_equipment ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.character_class_starting_equipment TO anon;
GRANT ALL ON TABLE public.character_class_starting_equipment TO authenticated;
GRANT ALL ON TABLE public.character_class_starting_equipment TO service_role;

CREATE INDEX idx_character_class_starting_equipment_class_id
  ON public.character_class_starting_equipment USING btree (character_class_id);

CREATE INDEX idx_character_class_starting_equipment_equipment_id
  ON public.character_class_starting_equipment USING btree (equipment_id);


--------------------------------------------------------------------------------
-- CHARACTER CLASS STARTING EQUIPMENT POLICIES
--------------------------------------------------------------------------------

CREATE POLICY "Users can read character class starting equipment"
ON public.character_class_starting_equipment
FOR SELECT TO anon, authenticated
USING (
  public.can_read_resource(character_class_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can create character class starting equipment"
ON public.character_class_starting_equipment
FOR INSERT TO authenticated
WITH CHECK (
  public.can_edit_resource(character_class_id)
  AND (equipment_id IS NULL OR public.can_read_resource(equipment_id))
);

CREATE POLICY "Creators and GMs can delete character class starting equipment"
ON public.character_class_starting_equipment
FOR DELETE TO authenticated
USING (public.can_edit_resource(character_class_id));
